### ISSUE TITLE
Steamゲームのテーブルを作成する

### ISSUE THREAD

**Issue by kinakomoch7** [vdslab/steam-suggester#42]
- 初期読み込みの際に時間かかる
- APIを複数回呼び出しているため、SteamAPIのアクセス制限にひっかかる
- データベースにゲームリストを保持してもいい？？

**Comment by kinakomoch7** [comment]
inoueの環境ではたまに大本のAPIがnullになってエラーになる
入れる価値ありかもしれない

**Comment by inoue021231** [comment]
作った、解決
